#! /bin/bash
#
# Helper to launch the service with activated virtualenv.
#
# The virtualenv needs to be active for uWSGI to work properly.

. /etc/default/jupyterhub
. /opt/venvs/jupyterhub/bin/activate
builtin cd /var/opt/jupyterhub

/usr/sbin/jupyterhub \
    --url=${JUPYTERHUB_BIND_URL:-"http://:8000"} \
    --log-level=${JUPYTERHUB_LOGLEVEL:-"INFO"} \
    --pid-file=/var/run/jupyterhub.pid \
    --config=${JUPYTERHUB_CONFDIR:-"/etc/jupyterhub"}/jupyterhub_config.py
#    --ssl-key my_ssl.key \
#    --ssl-cert my_ssl.cert \
