#! /bin/bash
#
# Helper to launch the service with activated virtualenv.
#
# The virtualenv needs to be active for uWSGI to work properly.

# Set up runtime environment
. /etc/default/jupyterhub
. /opt/venvs/jupyterhub/bin/activate
builtin cd /var/opt/jupyterhub

# PySpark / JVM settings
default_java_home=$(readlink /etc/alternatives/java 2>/dev/null)
default_java_home=${default_java_home%%/bin/*}
default_java_home=${default_java_home%%/jre}
export JAVA_HOME=${JUPYTERHUB_JAVA_HOME:-$default_java_home}
echo "$0: JAVA_HOME is '$JAVA_HOME'"

# Launch the server
/usr/sbin/jupyterhub \
    --url=${JUPYTERHUB_BIND_URL:-"http://:8000"} \
    --log-level=${JUPYTERHUB_LOGLEVEL:-"INFO"} \
    --pid-file=/var/run/jupyterhub.pid \
    --config=${JUPYTERHUB_CONFDIR:-"/etc/jupyterhub"}/jupyterhub_config.py
#    --ssl-key my_ssl.key \
#    --ssl-cert my_ssl.cert \
